version: '3.8'

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: pastebin_postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: pastebindb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pastebin-api:
    container_name: pastebin_web_api
    build:
      context: .
      dockerfile: PastebinSharer/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Port=5432;Database=pastebindb;Username=postgres;Password=123
    depends_on:
      postgres-db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: